name: Sync Secrets

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write
  pull-requests: write

jobs:
  sync-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      # - uses: webfactory/ssh-agent@v0.8.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Set up environment variables
        run: |
          echo "TEST1=${{ secrets.__TEST1 }}" >> $GITHUB_ENV

      - name: Store secret in .env file
        run: |
          echo "TEST1=${{ secrets.__TEST1 }}" >> .env

      - name: Copy files to Codespaces
        run: |
          CODESPACES=$(gh codespace list --org thejaswicy --json name)
          echo "CODESPACES: $CODESPACES"
          
          for CODESPACE_NAME in $(echo $CODESPACES | jq -r '.[].name'); do
            echo "Copying files to Codespace: $CODESPACE_NAME"
            gh codespace cp -c $CODESPACE_NAME .env remote:/workspaces/Devcontainers
          done
          
          echo "::set-output name=codespaces::$CODESPACES"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
